esphome:
  name: luminplant
  friendly_name: LuminPlant

packages:
  base: !include common/base_config.yaml
  light_ring: !include modules/light_ring.yaml
  light_sensor: !include modules/light_sensor.yaml
  ringlight: !include ringlight.yaml
  brightness: !include brightness.yaml
# temperature: !include modules/temperature.yaml #Included in climate
# humidity: !include modules/humidity.yaml #Included in climate
  soil: !include modules/soil_moisture.yaml
  climate: !include modules/climate.yaml
#  water: !include modules/water_level.yaml

#  # Only for homeassistant
#  # Only for esphome
buttons: !include buttons.yaml
