esphome:
  name: luminplant
  friendly_name: LuminPlant

#  Konfiguration (WLAN, OTA, Logger, API, ESP32-Board)
<<: !include common/base_config.yaml

# Modulweise Einbindung
<<: !include modules/light_ring.yaml
<<: !include modules/light_sensor.yaml
#<<: !include modules/soil_moisture.yaml
#<<: !include modules/water_level.yaml
#<<: !include modules/climate.yaml
